---

- name: Common tasks
  hosts: [all]
  tags: [common]
  roles: [{role: common}]

- name: Install required software on each host
  hosts: [all]
  roles:
    - {role: consul-master, tags: [consul]}
    - {role: docker, tags: [docker]}
