---

- name: Common tasks
  hosts: [all]
  tags: [common]
  roles: [{role: common}]

- name: Install required software on each host
  hosts: [all]
  roles: # order is important
    - {role: consul, tags: [consul]}
    - {role: glusterfs, tags: [glusterfs]}
    - {role: docker, tags: [docker]}
    - {role: nomad, tags: [nomad]}
