---

- name: Create a volume for the Nomad
  block:
    - name: Nomad | Make a directory for the bricks
      become: true
      ansible.builtin.file:
        path: /opt/glusterfs/bricks/nomad-storage/brick
        state: directory
        mode: 0750

    - name: Nomad | Make a gluster volume
      become: true
      # Docs: <https://docs.ansible.com/ansible/latest/collections/gluster/gluster/gluster_volume_module.html>
      gluster.gluster.gluster_volume:
        name: nomad-storage
        cluster: "{{ private_ip }},{% for host in glusterfs_join_hosts %}{{ hostvars[host]['private_ip'] }},{% endfor %}"
        replicas: "{{ (glusterfs_join_hosts | length) + 1 }}"
        bricks: /opt/glusterfs/bricks/nomad-storage/brick
        start_on_create: true
        state: present
        transport: tcp
        force: true
      run_once: true
