---

all:
  hosts:
    iddqd-uk-master-1:
      ansible_host: 192.168.56.116
      private_ip: 192.168.56.116
      consul_retry_join_hosts: [iddqd-uk-worker-1]
    iddqd-uk-worker-1:
      ansible_host: 192.168.56.117
      private_ip: 192.168.56.117
      consul_retry_join_hosts: [iddqd-uk-master-1]

  children:
    #consul_hosts:
    #  hosts:
    #    iddqd-uk-master-1: {}
    #    iddqd-uk-worker-1: {}
