---

all:
  hosts:
    iddqd-uk-node-1:
      ansible_host: 192.168.56.116
      private_ip: 192.168.56.116
      consul_retry_join_hosts: [iddqd-uk-node-2]
      nomad_retry_join_hosts: [iddqd-uk-node-2]
      glusterfs_join_hosts: [iddqd-uk-node-2]
    iddqd-uk-node-2:
      ansible_host: 192.168.56.117
      private_ip: 192.168.56.117
      consul_retry_join_hosts: [iddqd-uk-node-1]
      nomad_retry_join_hosts: [iddqd-uk-node-1]
      glusterfs_join_hosts: [iddqd-uk-node-1]

  children:
    #consul_hosts:
    #  hosts:
    #    iddqd-uk-node-1: {}
    #    iddqd-uk-node-2: {}
