---

ansible_user: user
ansible_port: 202 # aka SSH port
ansible_python_interpreter: /usr/bin/python3

consul_domain_name: consul.local.iddqd.uk
consul_http_port: 8500
consul_secret_key: "Ya8gOTDqQOwU/VZM6ZW1zzIjG4awADVlTEZ/Fi+MB9k="

nomad_secret_key: "baLVhqjEKeUkJi4do1M9VfJbKRfdUp4n5/vpBwyJSJ0="
